name: Testing the code 
on: [push]
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build the image
      run: docker build -t flask-hello-world .
    - name: run pytest
      run: docker run flask-hello-world pytest test.py
    - name: run flake8 tests
      run: docker run flask-hello-world flake8